version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  dialogger:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  data-import:
    build: ./data
    links:
      - mongo
